# Generated by Django 4.0.5 on 2022-07-03 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Like', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='Like.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrpas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
